---

- block:
  # We make the assumption, which I think is safe, that snap is already
  # installed.
  - name: install snap package
    shell: "snap install {{ item }} && snap refresh {{ item }}"
    with_items: "{{ snaps_to_install }}"

  - name: install classic snap packages
    shell: "snap install {{ item }} --classic && snap refresh {{ item }}"
    with_items: "{{ snaps_classic_to_install }}"

  become: yes
